var:
  url-repo: https://github.com/DaveMTK20002/Projet-Application-FNUAP.git

project:
  type: website

website:
  title: "IAGRIKOL: Analyse intelligente du sol"
  repo-url: "{{< meta var.url-repo >}}"
  repo-branch: main
  reader-mode: true
  navbar:
    background: "#447099"
    left:
      - icon: house
        href: index.qmd
        text: Home
      - text: Contexte
        menu:
          - href: doc/context1.qmd
            text: "Présentation de la compétition"
          - href: doc/context2.qmd
            text: "Présentation de l'équipe"
          - href: doc/context3.qmd
            text: "Prix reçus"
      - text: Avancement
        menu:
          - href: doc/avancee1.qmd
            text: "Introduction"
          - href: doc/avancee2.qmd
            text: "Méthodologie adoptée"
          - href: https://ludo2ne.github.io/Git-tuto/doc/presentation.html
            text: "Git"
            target: "_blank"
          - href: doc/avancee3.qmd
            text: "Deploiement du code"
      - text: Application
        menu:
          - href: doc/application1.qmd
            text: "Documentation"
          - href: doc/application2.qmd
            text: "Application"
    right:
      - icon: github
        href: "{{< meta var.url-repo >}}"
        target: "_blank"
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Code source]({{< meta var.url-repo >}}){.external target="_blank"}

format:
  html:
    theme:
      dark: solar
      light: cosmo
    css: styles.css
  revealjs:
    css: none