var:
  url-repo: https://github.com/DaveMTK20002/Projet-Application-FNUAP.git

project:
  type: website

website:
  title: "IAGRIKOL: Analyse intelligente du sol"
  repo-url: "{{< meta var.url-repo >}}"
  repo-branch: main
  reader-mode: true
  navbar:
    background: "#447099"
    left:
      - icon: house
        href: index.qmd
        text: Home
      - text: Contexte
        menu:
          - href: doc/context1.qmd
            text: "Présentation du projet"
          - href: doc/context2.qmd
            text: "Présentation de la compétition"
          - href: doc/context3.qmd
            text: "Equipe de développement"
      - text: Application
        menu:
          - href: doc/application1.qmd
            text: "Tester l'application"
          - href: doc/application2.qmd
            text: "Source de données"
    right:
      - icon: github
        href: "{{< meta var.url-repo >}}"
        target: "_blank"
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Code source]({{< meta var.url-repo >}}){.external target="_blank"}

format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
  revealjs:
    css: none