
---
title: "Autour de l'application"
description: "Sources de données"
author: "Davick MOUNTEKA"
format:
  html:
    toc: true
    toc-location: left
    toc-expand: 3
from: markdown+emoji
number-sections: true
---

### Problème des données

Un des principaux défis rencontrés dans ce projet est l'insuffisance des données sur les sols. A la base, l'idée principale était de pouvoir extraire des caractéristiques des sols (ph, teneur en sable, en carbone, etc) à partir d'une imagerie assez nette. Cela devait faire mobiliser plusieurs ressources d'ordres informationnel et informatique. Il a donc été pratiquement été impossible sous contrainte de ressources d'arriver jusque-là. De plus, il était prévu que ces images soient celles prises sur des sols correspondant au territoire Camerounais, puisque l'application est conçue dans ce cadre.

### Alternative trouvée

Vue l'insuffisance des données, nous avons opté pour une approche différente. Déjà, nous avons modélisé le caractère d'un sol à être adapté à la plantation d'une certaine culture à partir de l'analyse de ses caractéristiques physiques. On a également inclus les variables liées à la présence d'autres cultures sur le sol pouvant influer sur la plantation de cette culture. Aussi, nous avons considéré des cultures qui sont généralement cultivée au Cameroun (de façon non exhaustive vue la rareté des données au niveau national).

Pour finir, nous avons utilisé une base de données de la France portant sur certaines cultures et les caractéristiques des sols où elles avaient été implantées. Les cultures pertinentes que nous avons retenues pouvant être aussi cultivées au Cameroun sont:

- Le mais ;
- Le ble tendre ;
- L'orge ;
- Le bettrave à sucre.

A partir de ces données l'on a pu extraire les informations que l'on a finalement compactées dans un fichier excel qui a constitué notre base final.

Pour plus d'informations sur les données recueillies par la France, aller sur [Package R d'extraction des données](https://github.com/BjnNowak/frex){target="_blank"}.