
---
title: "Contexte et justification du projet"
description: "Journée de la fille scientifique"
author: "Davick MOUNTEKA"
format:
  html:
    toc: true
    toc-location: left
    toc-expand: 3
from: markdown+emoji
number-sections: true
---

## Autour de la journée

La semaine du 11 au 16 mars 2024 a été marquée par la SEMAINE DE LA FILLE SCIENTIFIQUE. Elle s'est tenue à l'Ecole Nationale Supérieure Polytechnique de Yaoundé (ENSPY). Son thème: "Scientifique et Leader, sommes-nous prêts à incarner ce modèle de femme?".

Cet évenement à été organisée par l'AFENSPY (Association des Filles de l'ENSPY). Elle était dirigée par le Bureau AMAZONE sous le haut Patronage de leurs excellences MINPROFF, MINDHU et MINJEC. Ceci, sous le co-parrainage de Mme la Directrice de la CCA, Mme la Présidente des Entreprises de l'Excellence du Cameroun et M. Le Représentant Résidant de l'IAI Cameroun. Les partenaires de marque étant le UNFPA (Fonds des Nations Unies pour les Activités en matière de Population) et l'OAPI (Organisation Africaine de la Propriété Intellectuelle).


<figure>
  <video width="300" controls>
    <source src="images/ouverture.mp4" type="video/mp4">
  </video>
  <figcaption>Résumé de la journée d'ouverture</figcaption>
</figure>


A l'occasion de cette journée, plusieurs activités étaient au programme, notamment:

- 

## Autour du concours du meilleur projet féminin d'innovation
