
---
title: "Contexte et justification du projet"
description: "Les Concepteurs"
author: "Davick MOUNTEKA"
format:
  html:
    toc: true
    toc-location: left
    toc-expand: 3
from: markdown+emoji
number-sections: true
---

## Avant de commencer {.unnumbered}

:scream: Comme vous pouvez le constater, le sujet de ce TP est lui aussi long. Cela ne doit pas vous effrayer.

Il mélange explications complètes et manipulations pour être au maximum autosuffisant.

**Vous n'allez surement pas terminer le sujet, ce n'est pas grave. Il est là pour vous aider lors du projet informatique.**

::: {.callout-note title="Objectifs"}
Dans ce TP vous allez : 

- Faire des appels à un webservice à la main avec *Insomnia*
- Faire des appels à un webservice avec la bibliothèque python *requests*
- Découvrir la page swagger d'un webservice
- Manipuler différents formats de données
- Créer un webservice avec le framework python *fastAPI*
:::



## Appeler un webservice à la main

La première partie de ce TP ne nécessite pas d'écrire du code, mais seulement de faire des requêtes à un webservice en utilisant le logiciel [Insomnia](https://insomnia.rest/){target="_blank"} installé sur votre machine.

### Webservices

::: {.callout-note}
**Webservice** : le terme webservice est un terme vaste et il serait compliqué d'en donner une définition courte ([article wikipedia](https://en.wikipedia.org/wiki/Web_service){target="_blank"}).

Dans le cadre du projet un webservice désigne une application accessible via le protocole HTTP (**H**yper**T**ext **T**ransfer **P**rotocol) qui respecte généralement l'architecture REST (**RE**presentational **S**tate **T**ransfer).

Mais il en existe d'autre comme SOAP (**S**imple **O**bjet- **A**ccess **P**rotocol) ou RPC (**R**emote **P**rocedure **C**all)
::: 

En d'autres termes, un webservice est une application accessible via le web que l'on va pouvoir **requêter** soit :

- pour obtenir des **ressources**
- pour **modifier** les ressources accessibles. 

Un webservice peut seulement avoir pour but d'être une **point d'accès unique et normalisé** à des données (comme une interface à une base de données), mais il peut également être une **manière de contrôler un système d'informations** (lancer des travaux, les mettre en attente, récupérer des résultats...)

Les webservices utilisent le protocole HTTP qui est le protocole du web (et pas d'internet). C'est celui que vous utilisez sans le savoir avec votre navigateur web. Requêter un webservice se fait presque comme requêter une page web. 

Pour cela il vous faut :

- l'adresse de la ressource, son *Uniforme Resource Identifier* (URI) 
  - c'est une notion plus générale que les *Uniforme Resource Locator* (URL)
- une méthode (GET, POST, PUT, DELETE, [liste des méthodes](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods){target="_blank"})
- et potentiellement des données

### Premières requêtes GET

- [ ] Lancez le programme **Insomnia**
  - Icone Windows en bas à gauche > 5-Informatique
- [ ] Créez une collection de requête 
    - bouton **Create** à droite
    - puis cliquez sur votre collection
- [ ] Créez une nouvelle requête 
    - en appuyant sur **CTRL+N**
    - donnez lui un nom 
    - vérifiez que c'est bien une requête de type **GET**

Dans la barre d'adresse, testez les requêtes des webservices ci-dessous :

- Regardez la réponse dans la partie droite de votre écran
- Quelles sont les similarités entre les réponses ?